/* tslint:disable */
/* eslint-disable */
/**
 * Croqueteria - API Documentation
 * Endpoints for Croqueteria API, a service that allows to describe, rate and discuss the most delicious croquettes around the globe.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentUpdateRequest
 */
export interface CommentUpdateRequest {
    /**
     * Updated text of the comment, optional but must be between 3 and 10,000 characters if provided.
     * @type {string}
     * @memberof CommentUpdateRequest
     */
    comment?: string;
}

/**
 * Check if a given object implements the CommentUpdateRequest interface.
 */
export function instanceOfCommentUpdateRequest(value: object): value is CommentUpdateRequest {
    return true;
}

export function CommentUpdateRequestFromJSON(json: any): CommentUpdateRequest {
    return CommentUpdateRequestFromJSONTyped(json, false);
}

export function CommentUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function CommentUpdateRequestToJSON(json: any): CommentUpdateRequest {
    return CommentUpdateRequestToJSONTyped(json, false);
}

export function CommentUpdateRequestToJSONTyped(value?: CommentUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': value['comment'],
    };
}

