/* tslint:disable */
/* eslint-disable */
/**
 * Croqueteria - API Documentation
 * Endpoints for Croqueteria API, a service that allows to describe, rate and discuss the most delicious croquettes around the globe.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentCreateRequest
 */
export interface CommentCreateRequest {
    /**
     * ID of the croquette to comment on
     * @type {number}
     * @memberof CommentCreateRequest
     */
    croquetteId: number;
    /**
     * Text content of the comment
     * @type {string}
     * @memberof CommentCreateRequest
     */
    comment: string;
}

/**
 * Check if a given object implements the CommentCreateRequest interface.
 */
export function instanceOfCommentCreateRequest(value: object): value is CommentCreateRequest {
    if (!('croquetteId' in value) || value['croquetteId'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function CommentCreateRequestFromJSON(json: any): CommentCreateRequest {
    return CommentCreateRequestFromJSONTyped(json, false);
}

export function CommentCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'croquetteId': json['croquetteId'],
        'comment': json['comment'],
    };
}

export function CommentCreateRequestToJSON(json: any): CommentCreateRequest {
    return CommentCreateRequestToJSONTyped(json, false);
}

export function CommentCreateRequestToJSONTyped(value?: CommentCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'croquetteId': value['croquetteId'],
        'comment': value['comment'],
    };
}

