/* tslint:disable */
/* eslint-disable */
/**
 * Croqueteria - API Documentation
 * Endpoints for Croqueteria API, a service that allows to describe, rate and discuss the most delicious croquettes around the globe.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentResponse
 */
export interface CommentResponse {
    /**
     * Unique identifier of the comment
     * @type {number}
     * @memberof CommentResponse
     */
    id?: number;
    /**
     * ID of the croquette this comment belongs to
     * @type {number}
     * @memberof CommentResponse
     */
    croquetteId?: number;
    /**
     * ID of the user who made the comment
     * @type {number}
     * @memberof CommentResponse
     */
    userId?: number;
    /**
     * Username of the commenter
     * @type {string}
     * @memberof CommentResponse
     */
    userName?: string;
    /**
     * Content of the comment
     * @type {string}
     * @memberof CommentResponse
     */
    comment: string;
    /**
     * Timestamp when the comment was created
     * @type {Date}
     * @memberof CommentResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the CommentResponse interface.
 */
export function instanceOfCommentResponse(value: object): value is CommentResponse {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CommentResponseFromJSON(json: any): CommentResponse {
    return CommentResponseFromJSONTyped(json, false);
}

export function CommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'croquetteId': json['croquetteId'] == null ? undefined : json['croquetteId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'comment': json['comment'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function CommentResponseToJSON(json: any): CommentResponse {
    return CommentResponseToJSONTyped(json, false);
}

export function CommentResponseToJSONTyped(value?: CommentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'croquetteId': value['croquetteId'],
        'userId': value['userId'],
        'userName': value['userName'],
        'comment': value['comment'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

