/* tslint:disable */
/* eslint-disable */
/**
 * Croqueteria - API Documentation
 * Endpoints for Croqueteria API, a service that allows to describe, rate and discuss the most delicious croquettes around the globe.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CroquetteRecommendationResponse
 */
export interface CroquetteRecommendationResponse {
    /**
     * 
     * @type {number}
     * @memberof CroquetteRecommendationResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CroquetteRecommendationResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CroquetteRecommendationResponse
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof CroquetteRecommendationResponse
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof CroquetteRecommendationResponse
     */
    crunchiness: number;
    /**
     * 
     * @type {number}
     * @memberof CroquetteRecommendationResponse
     */
    spiciness: number;
    /**
     * 
     * @type {boolean}
     * @memberof CroquetteRecommendationResponse
     */
    vegan: boolean;
    /**
     * 
     * @type {string}
     * @memberof CroquetteRecommendationResponse
     */
    form: string;
    /**
     * 
     * @type {string}
     * @memberof CroquetteRecommendationResponse
     */
    imageUrl: string;
    /**
     * 
     * @type {Date}
     * @memberof CroquetteRecommendationResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CroquetteRecommendationResponse
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof CroquetteRecommendationResponse
     */
    averageRating?: number;
    /**
     * 
     * @type {number}
     * @memberof CroquetteRecommendationResponse
     */
    score?: number;
}

/**
 * Check if a given object implements the CroquetteRecommendationResponse interface.
 */
export function instanceOfCroquetteRecommendationResponse(value: object): value is CroquetteRecommendationResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('crunchiness' in value) || value['crunchiness'] === undefined) return false;
    if (!('spiciness' in value) || value['spiciness'] === undefined) return false;
    if (!('vegan' in value) || value['vegan'] === undefined) return false;
    if (!('form' in value) || value['form'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    return true;
}

export function CroquetteRecommendationResponseFromJSON(json: any): CroquetteRecommendationResponse {
    return CroquetteRecommendationResponseFromJSONTyped(json, false);
}

export function CroquetteRecommendationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CroquetteRecommendationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'country': json['country'],
        'description': json['description'],
        'crunchiness': json['crunchiness'],
        'spiciness': json['spiciness'],
        'vegan': json['vegan'],
        'form': json['form'],
        'imageUrl': json['imageUrl'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'averageRating': json['averageRating'] == null ? undefined : json['averageRating'],
        'score': json['score'] == null ? undefined : json['score'],
    };
}

export function CroquetteRecommendationResponseToJSON(json: any): CroquetteRecommendationResponse {
    return CroquetteRecommendationResponseToJSONTyped(json, false);
}

export function CroquetteRecommendationResponseToJSONTyped(value?: CroquetteRecommendationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'country': value['country'],
        'description': value['description'],
        'crunchiness': value['crunchiness'],
        'spiciness': value['spiciness'],
        'vegan': value['vegan'],
        'form': value['form'],
        'imageUrl': value['imageUrl'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'averageRating': value['averageRating'],
        'score': value['score'],
    };
}

