/* tslint:disable */
/* eslint-disable */
/**
 * Croqueteria - API Documentation
 * Endpoints for Croqueteria API, a service that allows to describe, rate and discuss the most delicious croquettes around the globe.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CroquetteResponse
 */
export interface CroquetteResponse {
    /**
     * Unique identifier of the croquette
     * @type {number}
     * @memberof CroquetteResponse
     */
    id?: number;
    /**
     * Name of the croquette
     * @type {string}
     * @memberof CroquetteResponse
     */
    name: string;
    /**
     * Country of origin
     * @type {string}
     * @memberof CroquetteResponse
     */
    country: string;
    /**
     * Detailed description of the croquette
     * @type {string}
     * @memberof CroquetteResponse
     */
    description: string;
    /**
     * Crunchiness level (1 to 5)
     * @type {number}
     * @memberof CroquetteResponse
     */
    crunchiness: number;
    /**
     * Spiciness level (1 to 5)
     * @type {number}
     * @memberof CroquetteResponse
     */
    spiciness: number;
    /**
     * Indicates if the croquette is vegan
     * @type {boolean}
     * @memberof CroquetteResponse
     */
    vegan: boolean;
    /**
     * Shape or form of the croquette
     * @type {string}
     * @memberof CroquetteResponse
     */
    form: string;
    /**
     * URL to an image of the croquette
     * @type {string}
     * @memberof CroquetteResponse
     */
    imageUrl: string;
    /**
     * Date when the croquette was created
     * @type {Date}
     * @memberof CroquetteResponse
     */
    createdAt?: Date;
    /**
     * Date when the croquette was last updated
     * @type {Date}
     * @memberof CroquetteResponse
     */
    updatedAt?: Date;
    /**
     * Average rating from users
     * @type {number}
     * @memberof CroquetteResponse
     */
    averageRating?: number;
}

/**
 * Check if a given object implements the CroquetteResponse interface.
 */
export function instanceOfCroquetteResponse(value: object): value is CroquetteResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('crunchiness' in value) || value['crunchiness'] === undefined) return false;
    if (!('spiciness' in value) || value['spiciness'] === undefined) return false;
    if (!('vegan' in value) || value['vegan'] === undefined) return false;
    if (!('form' in value) || value['form'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    return true;
}

export function CroquetteResponseFromJSON(json: any): CroquetteResponse {
    return CroquetteResponseFromJSONTyped(json, false);
}

export function CroquetteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CroquetteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'country': json['country'],
        'description': json['description'],
        'crunchiness': json['crunchiness'],
        'spiciness': json['spiciness'],
        'vegan': json['vegan'],
        'form': json['form'],
        'imageUrl': json['imageUrl'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'averageRating': json['averageRating'] == null ? undefined : json['averageRating'],
    };
}

export function CroquetteResponseToJSON(json: any): CroquetteResponse {
    return CroquetteResponseToJSONTyped(json, false);
}

export function CroquetteResponseToJSONTyped(value?: CroquetteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'country': value['country'],
        'description': value['description'],
        'crunchiness': value['crunchiness'],
        'spiciness': value['spiciness'],
        'vegan': value['vegan'],
        'form': value['form'],
        'imageUrl': value['imageUrl'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'averageRating': value['averageRating'],
    };
}

