/* tslint:disable */
/* eslint-disable */
/**
 * Croqueteria - API Documentation
 * Endpoints for Croqueteria API, a service that allows to describe, rate and discuss the most delicious croquettes around the globe.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CroquetteLLMRecommendationRequest
 */
export interface CroquetteLLMRecommendationRequest {
    /**
     * 
     * @type {string}
     * @memberof CroquetteLLMRecommendationRequest
     */
    description: string;
}

/**
 * Check if a given object implements the CroquetteLLMRecommendationRequest interface.
 */
export function instanceOfCroquetteLLMRecommendationRequest(value: object): value is CroquetteLLMRecommendationRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CroquetteLLMRecommendationRequestFromJSON(json: any): CroquetteLLMRecommendationRequest {
    return CroquetteLLMRecommendationRequestFromJSONTyped(json, false);
}

export function CroquetteLLMRecommendationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CroquetteLLMRecommendationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
    };
}

export function CroquetteLLMRecommendationRequestToJSON(json: any): CroquetteLLMRecommendationRequest {
    return CroquetteLLMRecommendationRequestToJSONTyped(json, false);
}

export function CroquetteLLMRecommendationRequestToJSONTyped(value?: CroquetteLLMRecommendationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
    };
}

