/* tslint:disable */
/* eslint-disable */
/**
 * Croqueteria - API Documentation
 * Endpoints for Croqueteria API, a service that allows to describe, rate and discuss the most delicious croquettes around the globe.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingCreateRequest
 */
export interface RatingCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof RatingCreateRequest
     */
    croquetteId: number;
    /**
     * 
     * @type {number}
     * @memberof RatingCreateRequest
     */
    rating: number;
}

/**
 * Check if a given object implements the RatingCreateRequest interface.
 */
export function instanceOfRatingCreateRequest(value: object): value is RatingCreateRequest {
    if (!('croquetteId' in value) || value['croquetteId'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    return true;
}

export function RatingCreateRequestFromJSON(json: any): RatingCreateRequest {
    return RatingCreateRequestFromJSONTyped(json, false);
}

export function RatingCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'croquetteId': json['croquetteId'],
        'rating': json['rating'],
    };
}

export function RatingCreateRequestToJSON(json: any): RatingCreateRequest {
    return RatingCreateRequestToJSONTyped(json, false);
}

export function RatingCreateRequestToJSONTyped(value?: RatingCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'croquetteId': value['croquetteId'],
        'rating': value['rating'],
    };
}

