/* tslint:disable */
/* eslint-disable */
/**
 * Croqueteria - API Documentation
 * Endpoints for Croqueteria API, a service that allows to describe, rate and discuss the most delicious croquettes around the globe.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingUpdateRequest
 */
export interface RatingUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof RatingUpdateRequest
     */
    rating?: number;
}

/**
 * Check if a given object implements the RatingUpdateRequest interface.
 */
export function instanceOfRatingUpdateRequest(value: object): value is RatingUpdateRequest {
    return true;
}

export function RatingUpdateRequestFromJSON(json: any): RatingUpdateRequest {
    return RatingUpdateRequestFromJSONTyped(json, false);
}

export function RatingUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function RatingUpdateRequestToJSON(json: any): RatingUpdateRequest {
    return RatingUpdateRequestToJSONTyped(json, false);
}

export function RatingUpdateRequestToJSONTyped(value?: RatingUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating': value['rating'],
    };
}

