version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - SWAGGER_UI_URL=http://localhost:8080/swagger-ui.html
      - SPRING_CROQUETERIA_LLM_URL=http://localhost:11434/api/generate
      - SPRING_CROQUETERIA_JWT_SECRET=replace with your secret
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  ollama-llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
